
platform :ios, '10.0'

target 'SmartNotificationsDemo' do
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'IncomingSDK/IncomingPVN', '~> 2.6.2'
end
